services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
      args:
        NODE_VERSION: ${NODE_VERSION}
    ports:
      - "4000:4000"
    env_file:
      - ./backend/.env
    depends_on:
      - redis
    volumes:
      - ./backend:/app
      - /app/node_modules
      - ./frontend/public/result-templates:/app/result-templates:ro
      - ../votedots_local_storage:/votedots-storage
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
      args:
        NODE_VERSION: ${NODE_VERSION}
    ports:
      - "5173:5173"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules

  redis:
    image: redis:${REDIS_VERSION}-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  redis_data:
