ARG NODE_VERSION
FROM node:${NODE_VERSION}-alpine

WORKDIR /app

RUN npm install -g ts-node typescript nodemon

COPY package*.json ./

RUN npm install

COPY . .

EXPOSE 4000

CMD ["nodemon", "--exec", "ts-node", "src/index.ts"]