import type { CSSProperties } from "react";
import type { PageTheme } from "../tokens/page-theme.types";

export function buildPageThemeStyle(theme: PageTheme): CSSProperties {
  return {
    colorScheme: theme.colorScheme ?? "light",
    "--page-theme-text-primary": theme.textPrimary,
    "--page-theme-text-secondary": theme.textSecondary,
    "--page-theme-text-tertiary": theme.textTertiary,
    "--page-theme-page-background": theme.pageBackground,
    "--page-theme-page-pattern-dot": theme.pagePatternDot,
    "--page-theme-panel-background": theme.panelBackground,
    "--page-theme-surface-primary": theme.surfacePrimary,
    "--page-theme-surface-elevated": theme.surfaceElevated,
    "--page-theme-surface-secondary": theme.surfaceSecondary,
    "--page-theme-border-primary": theme.borderPrimary,
    "--page-theme-border-secondary": theme.borderSecondary,
    "--page-theme-primary-action": theme.primaryAction,
    "--page-theme-primary-action-hover": theme.primaryActionHover,
    "--page-theme-primary-action-text": theme.primaryActionText,
    "--page-theme-accent-warm": theme.accentWarm,
    "--page-theme-accent-warm-soft": theme.accentWarmSoft,
    "--page-theme-alert": theme.alert,
    "--page-theme-alert-soft": theme.alertSoft,
    "--page-theme-overlay": theme.overlay,
    "--background": theme.surfacePrimary,
    "--foreground": theme.textPrimary,
    "--card": theme.surfacePrimary,
    "--card-foreground": theme.textPrimary,
    "--popover": theme.surfaceElevated,
    "--popover-foreground": theme.textPrimary,
    "--primary": theme.primaryAction,
    "--primary-foreground": theme.primaryActionText,
    "--secondary": theme.surfaceSecondary,
    "--secondary-foreground": theme.textPrimary,
    "--muted": theme.surfaceSecondary,
    "--muted-foreground": theme.textSecondary,
    "--accent": theme.surfaceSecondary,
    "--accent-foreground": theme.textPrimary,
    "--border": theme.borderPrimary,
    "--input": theme.borderPrimary,
    "--ring": theme.primaryAction,
  } as CSSProperties;
}
